### ISSUE TITLE
KeyError in mkbins.py

### ISSUE THREAD

**Issue by vargatn** [vargatn/xpipe#4]
From Maria Elidaiana da S. Pereira

`Traceback (most recent call last):
  File "mkbins.py", line 22, in <module>
    randoms = parbins.prepare_random()
  File "/home/s1/mariaeli/mylibs/xpipe/xpipe/xhandle/parbins.py", line 568, in prepare_random
    data, fullcat = load_randcat(params, fullpaths)
  File "/home/s1/mariaeli/mylibs/xpipe/xpipe/xhandle/parbins.py", line 366, in load_randcat
    qlist[:, ival] = randcat[randkey[colname]]
KeyError: 'q2'

edit the file /xpipe/xpipe/xhandle/parbins.py by changing the line "nq = len(randkey.keys()) - 3" to "nq = len(randkey.keys()) - 4"`

**Comment by hywu** [comment]
Would it be possible to check whether the key e.g. 'q2' exists?

**Comment by vargatn** [comment]
After some digging I think this might be due to some setting in the config files, could you post them somewhere? I could not reproduce  the problem with my own settings
